# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Nov  8 22:41:27 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("assets/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.viewOne = QtGui.QFrame(MainWindow)
        self.viewOne.setEnabled(True)
        self.viewOne.setGeometry(QtCore.QRect(10, 600, 580, 580))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewOne.sizePolicy().hasHeightForWidth())
        self.viewOne.setSizePolicy(sizePolicy)
        self.viewOne.setMinimumSize(QtCore.QSize(580, 580))
        self.viewOne.setMaximumSize(QtCore.QSize(580, 580))
        self.viewOne.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewOne.setStyleSheet(_fromUtf8(""))
        self.viewOne.setFrameShape(QtGui.QFrame.StyledPanel)
        self.viewOne.setFrameShadow(QtGui.QFrame.Raised)
        self.viewOne.setObjectName(_fromUtf8("viewOne"))
        self.gridLayout = QtGui.QGridLayout(self.viewOne)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.floorNext = QtGui.QPushButton(self.viewOne)
        self.floorNext.setEnabled(False)
        self.floorNext.setMinimumSize(QtCore.QSize(150, 0))
        self.floorNext.setObjectName(_fromUtf8("floorNext"))
        self.gridLayout.addWidget(self.floorNext, 5, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.viewOne)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(150, 150))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("assets/logo.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.floorImage = QtGui.QLabel(self.viewOne)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorImage.sizePolicy().hasHeightForWidth())
        self.floorImage.setSizePolicy(sizePolicy)
        self.floorImage.setMinimumSize(QtCore.QSize(400, 0))
        self.floorImage.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.floorImage.setFont(font)
        self.floorImage.setText(_fromUtf8(""))
        self.floorImage.setPixmap(QtGui.QPixmap(_fromUtf8("assets/0U.jpg")))
        self.floorImage.setScaledContents(True)
        self.floorImage.setAlignment(QtCore.Qt.AlignCenter)
        self.floorImage.setObjectName(_fromUtf8("floorImage"))
        self.gridLayout.addWidget(self.floorImage, 0, 0, 6, 1)
        self.selectFloor = QtGui.QGroupBox(self.viewOne)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFloor.sizePolicy().hasHeightForWidth())
        self.selectFloor.setSizePolicy(sizePolicy)
        self.selectFloor.setMinimumSize(QtCore.QSize(150, 0))
        self.selectFloor.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.selectFloor.setFont(font)
        self.selectFloor.setAlignment(QtCore.Qt.AlignCenter)
        self.selectFloor.setObjectName(_fromUtf8("selectFloor"))
        self.gridLayout_6 = QtGui.QGridLayout(self.selectFloor)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.secondFloor = QtGui.QRadioButton(self.selectFloor)
        self.secondFloor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.secondFloor.setObjectName(_fromUtf8("secondFloor"))
        self.gridLayout_5.addWidget(self.secondFloor, 2, 0, 1, 1)
        self.firstFloor = QtGui.QRadioButton(self.selectFloor)
        self.firstFloor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.firstFloor.setObjectName(_fromUtf8("firstFloor"))
        self.gridLayout_5.addWidget(self.firstFloor, 1, 0, 1, 1)
        self.groundFloor = QtGui.QRadioButton(self.selectFloor)
        self.groundFloor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groundFloor.setChecked(True)
        self.groundFloor.setObjectName(_fromUtf8("groundFloor"))
        self.gridLayout_5.addWidget(self.groundFloor, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.selectFloor, 1, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.viewOne)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.selectRoom = QtGui.QComboBox(self.groupBox)
        self.selectRoom.setObjectName(_fromUtf8("selectRoom"))
        self.gridLayout_8.addWidget(self.selectRoom, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 2, 1, 1)
        self.selectWing = QtGui.QGroupBox(self.viewOne)
        self.selectWing.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectWing.sizePolicy().hasHeightForWidth())
        self.selectWing.setSizePolicy(sizePolicy)
        self.selectWing.setAlignment(QtCore.Qt.AlignCenter)
        self.selectWing.setObjectName(_fromUtf8("selectWing"))
        self.gridLayout_7 = QtGui.QGridLayout(self.selectWing)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.u = QtGui.QRadioButton(self.selectWing)
        self.u.setChecked(True)
        self.u.setObjectName(_fromUtf8("u"))
        self.gridLayout_7.addWidget(self.u, 0, 0, 1, 1)
        self.v = QtGui.QRadioButton(self.selectWing)
        self.v.setObjectName(_fromUtf8("v"))
        self.gridLayout_7.addWidget(self.v, 0, 1, 1, 1)
        self.w = QtGui.QRadioButton(self.selectWing)
        self.w.setObjectName(_fromUtf8("w"))
        self.gridLayout_7.addWidget(self.w, 0, 2, 1, 1)
        self.z = QtGui.QRadioButton(self.selectWing)
        self.z.setObjectName(_fromUtf8("z"))
        self.gridLayout_7.addWidget(self.z, 1, 2, 1, 1)
        self.y = QtGui.QRadioButton(self.selectWing)
        self.y.setObjectName(_fromUtf8("y"))
        self.gridLayout_7.addWidget(self.y, 1, 1, 1, 1)
        self.x = QtGui.QRadioButton(self.selectWing)
        self.x.setObjectName(_fromUtf8("x"))
        self.gridLayout_7.addWidget(self.x, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.selectWing, 2, 2, 1, 1)
        self.viewTwo = QtGui.QFrame(MainWindow)
        self.viewTwo.setGeometry(QtCore.QRect(10, 600, 578, 572))
        self.viewTwo.setStyleSheet(_fromUtf8(""))
        self.viewTwo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.viewTwo.setFrameShadow(QtGui.QFrame.Raised)
        self.viewTwo.setObjectName(_fromUtf8("viewTwo"))
        self.gridLayout_2 = QtGui.QGridLayout(self.viewTwo)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.roomNext = QtGui.QPushButton(self.viewTwo)
        self.roomNext.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roomNext.sizePolicy().hasHeightForWidth())
        self.roomNext.setSizePolicy(sizePolicy)
        self.roomNext.setMinimumSize(QtCore.QSize(150, 0))
        self.roomNext.setMaximumSize(QtCore.QSize(75, 16777215))
        self.roomNext.setObjectName(_fromUtf8("roomNext"))
        self.gridLayout_2.addWidget(self.roomNext, 2, 4, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.viewTwo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scanInfo = QtGui.QPlainTextEdit(self.groupBox_2)
        self.scanInfo.setFrameShape(QtGui.QFrame.Box)
        self.scanInfo.setFrameShadow(QtGui.QFrame.Plain)
        self.scanInfo.setReadOnly(True)
        self.scanInfo.setBackgroundVisible(False)
        self.scanInfo.setCenterOnScroll(False)
        self.scanInfo.setObjectName(_fromUtf8("scanInfo"))
        self.verticalLayout.addWidget(self.scanInfo)
        self.scanButton = QtGui.QPushButton(self.groupBox_2)
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.verticalLayout.addWidget(self.scanButton)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.viewTwo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(150, 150))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("assets/logo.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.roomImage = QtGui.QLabel(self.viewTwo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roomImage.sizePolicy().hasHeightForWidth())
        self.roomImage.setSizePolicy(sizePolicy)
        self.roomImage.setMinimumSize(QtCore.QSize(400, 0))
        self.roomImage.setMaximumSize(QtCore.QSize(400, 16777215))
        self.roomImage.setLineWidth(0)
        self.roomImage.setText(_fromUtf8(""))
        self.roomImage.setPixmap(QtGui.QPixmap(_fromUtf8("assets/rooms/U103.jpg")))
        self.roomImage.setScaledContents(True)
        self.roomImage.setObjectName(_fromUtf8("roomImage"))
        self.gridLayout_2.addWidget(self.roomImage, 0, 0, 3, 1)
        self.viewThree = QtGui.QFrame(MainWindow)
        self.viewThree.setGeometry(QtCore.QRect(10, 10, 581, 581))
        self.viewThree.setStyleSheet(_fromUtf8(""))
        self.viewThree.setFrameShape(QtGui.QFrame.StyledPanel)
        self.viewThree.setFrameShadow(QtGui.QFrame.Raised)
        self.viewThree.setObjectName(_fromUtf8("viewThree"))
        self.gridLayout_3 = QtGui.QGridLayout(self.viewThree)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.saveFileBox = QtGui.QGroupBox(self.viewThree)
        self.saveFileBox.setAlignment(QtCore.Qt.AlignCenter)
        self.saveFileBox.setObjectName(_fromUtf8("saveFileBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.saveFileBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.saveInfo = QtGui.QLabel(self.saveFileBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saveInfo.setFont(font)
        self.saveInfo.setObjectName(_fromUtf8("saveInfo"))
        self.gridLayout_10.addWidget(self.saveInfo, 0, 1, 1, 1)
        self.saveData2 = QtGui.QLabel(self.saveFileBox)
        self.saveData2.setObjectName(_fromUtf8("saveData2"))
        self.gridLayout_10.addWidget(self.saveData2, 2, 1, 1, 1)
        self.saveFileBttn = QtGui.QPushButton(self.saveFileBox)
        self.saveFileBttn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveFileBttn.sizePolicy().hasHeightForWidth())
        self.saveFileBttn.setSizePolicy(sizePolicy)
        self.saveFileBttn.setObjectName(_fromUtf8("saveFileBttn"))
        self.gridLayout_10.addWidget(self.saveFileBttn, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.saveFileLoc = QtGui.QLabel(self.saveFileBox)
        self.saveFileLoc.setObjectName(_fromUtf8("saveFileLoc"))
        self.gridLayout_10.addWidget(self.saveFileLoc, 4, 1, 1, 1)
        self.logFile = QtGui.QRadioButton(self.saveFileBox)
        self.logFile.setObjectName(_fromUtf8("logFile"))
        self.gridLayout_10.addWidget(self.logFile, 2, 3, 1, 1)
        self.saveData1 = QtGui.QLabel(self.saveFileBox)
        self.saveData1.setObjectName(_fromUtf8("saveData1"))
        self.gridLayout_10.addWidget(self.saveData1, 1, 1, 1, 1)
        self.csv = QtGui.QRadioButton(self.saveFileBox)
        self.csv.setObjectName(_fromUtf8("csv"))
        self.gridLayout_10.addWidget(self.csv, 0, 3, 1, 1)
        self.saveFileIcon = QtGui.QLabel(self.saveFileBox)
        self.saveFileIcon.setMaximumSize(QtCore.QSize(110, 115))
        self.saveFileIcon.setText(_fromUtf8(""))
        self.saveFileIcon.setPixmap(QtGui.QPixmap(_fromUtf8("assets/saveIcon.png")))
        self.saveFileIcon.setScaledContents(True)
        self.saveFileIcon.setMargin(5)
        self.saveFileIcon.setObjectName(_fromUtf8("saveFileIcon"))
        self.gridLayout_10.addWidget(self.saveFileIcon, 0, 0, 5, 1)
        self.line = QtGui.QFrame(self.saveFileBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_10.addWidget(self.line, 0, 2, 5, 1)
        self.database = QtGui.QRadioButton(self.saveFileBox)
        self.database.setObjectName(_fromUtf8("database"))
        self.gridLayout_10.addWidget(self.database, 1, 3, 1, 1)
        self.allFiles = QtGui.QRadioButton(self.saveFileBox)
        self.allFiles.setObjectName(_fromUtf8("allFiles"))
        self.gridLayout_10.addWidget(self.allFiles, 3, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.saveFileBox, 1, 0, 1, 3)
        self.bannerImage = QtGui.QLabel(self.viewThree)
        self.bannerImage.setText(_fromUtf8(""))
        self.bannerImage.setPixmap(QtGui.QPixmap(_fromUtf8("assets/teamAwesome.png")))
        self.bannerImage.setAlignment(QtCore.Qt.AlignCenter)
        self.bannerImage.setObjectName(_fromUtf8("bannerImage"))
        self.gridLayout_3.addWidget(self.bannerImage, 2, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.restartButton = QtGui.QPushButton(self.viewThree)
        self.restartButton.setObjectName(_fromUtf8("restartButton"))
        self.gridLayout_3.addWidget(self.restartButton, 3, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.viewThree)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dataTable = QtGui.QTableWidget(self.groupBox_3)
        self.dataTable.setMaximumSize(QtCore.QSize(16777215, 175))
        self.dataTable.setFrameShape(QtGui.QFrame.Box)
        self.dataTable.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.dataTable.setShowGrid(True)
        self.dataTable.setObjectName(_fromUtf8("dataTable"))
        self.dataTable.setColumnCount(7)
        self.dataTable.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setItem(0, 6, item)
        self.dataTable.horizontalHeader().setDefaultSectionSize(70)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.dataTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.dataTable, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 3)
        self.exitButton = QtGui.QPushButton(self.viewThree)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.gridLayout_3.addWidget(self.exitButton, 3, 2, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wifi Sniffer", None))
        self.floorNext.setText(_translate("MainWindow", "Next", None))
        self.selectFloor.setTitle(_translate("MainWindow", " Please Select a Floor ", None))
        self.secondFloor.setText(_translate("MainWindow", "Second Floor", None))
        self.firstFloor.setText(_translate("MainWindow", "First Floor", None))
        self.groundFloor.setText(_translate("MainWindow", "Ground Floor", None))
        self.groupBox.setTitle(_translate("MainWindow", " Select Room ", None))
        self.selectWing.setTitle(_translate("MainWindow", " Select Wing ", None))
        self.u.setText(_translate("MainWindow", "U", None))
        self.v.setText(_translate("MainWindow", "V", None))
        self.w.setText(_translate("MainWindow", "W", None))
        self.z.setText(_translate("MainWindow", "Z", None))
        self.y.setText(_translate("MainWindow", "Y", None))
        self.x.setText(_translate("MainWindow", "X", None))
        self.roomNext.setText(_translate("MainWindow", "Next", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Room Information", None))
        self.scanInfo.setPlainText(_translate("MainWindow", "Stand at the North most point of the room and click the scan button, Repeat these steps for each point as requested.\n"
"\n"
"Once the scan is complete the results will be displayed.", None))
        self.scanButton.setText(_translate("MainWindow", "Scan North", None))
        self.saveFileBox.setTitle(_translate("MainWindow", "Save File", None))
        self.saveInfo.setText(_translate("MainWindow", "Save Information:", None))
        self.saveData2.setText(_translate("MainWindow", "File will be saved in the programs directory.", None))
        self.saveFileBttn.setText(_translate("MainWindow", "Save File", None))
        self.saveFileLoc.setText(_translate("MainWindow", "", None))
        self.logFile.setText(_translate("MainWindow", ".log - Log file", None))
        self.saveData1.setText(_translate("MainWindow", "Export the data as a file of your choice.", None))
        self.csv.setText(_translate("MainWindow", ".csv - Comma Seperated Value", None))
        self.database.setText(_translate("MainWindow", ".db - Database", None))
        self.allFiles.setText(_translate("MainWindow", "Export all file types", None))
        self.restartButton.setText(_translate("MainWindow", "Restart", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gathered Data", None))
        item = self.dataTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "N", None))
        item = self.dataTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "S", None))
        item = self.dataTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "E", None))
        item = self.dataTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "W", None))
        item = self.dataTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "C", None))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Gateway", None))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Access Point", None))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Loss (%)", None))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Delay (ms)", None))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quality", None))
        item = self.dataTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Signal (dbm)", None))
        item = self.dataTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Speed (Mb)", None))
        __sortingEnabled = self.dataTable.isSortingEnabled()
        self.dataTable.setSortingEnabled(False)
        item = self.dataTable.item(0, 0)
        item.setText(_translate("MainWindow", " ", None))
        item = self.dataTable.item(0, 1)
        item.setText(_translate("MainWindow", " ", None))
        item = self.dataTable.item(0, 2)
        item.setText(_translate("MainWindow", " ", None))
        item = self.dataTable.item(0, 3)
        item.setText(_translate("MainWindow", " ", None))
        item = self.dataTable.item(0, 4)
        item.setText(_translate("MainWindow",  " ", None))
        item = self.dataTable.item(0, 5)
        item.setText(_translate("MainWindow", " ", None))
        item = self.dataTable.item(0, 6)
        item.setText(_translate("MainWindow", " ", None))
        self.dataTable.setSortingEnabled(__sortingEnabled)
        self.exitButton.setText(_translate("MainWindow", "Exit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

